J-F-Liu/lopdf

- src/datetime.rs
- src/document.rs
- src/encodings/mod.rs
- src/object.rs
- src/parser.rs
- src/processor.rs
- src/reader.rs
- src/writer.rs
- src/xref.rs
The changes were suggested by clippy.
> Improve codestyle (simplify loops, remove closures, use is_empty() etc.)

- src/reader.rs
I found that loading the documents linked below makes lopdf panic on bad slice indexes. This PR fixes that panic, and several other similar cases in the same file.
These PDFs have bad offsets for their cross references that point past the end of the file. Other PDF readers can open them, though pdf.js warns in the console that it reindexes all the PDF objects when doing so. Future work could recover from a bad or missing cross reference, this PR only returns an error rather than panicking on such files.
https://oig.justice.gov/reports/plus/a0519/final.pdf
http://www.loc.gov/static/portals/about/office-of-the-inspector-general/documents/rpt2008marchITSlongdistsvc.pdf
> Check offsets read from file to avoid panics

- Cargo.toml
- src/object_stream.rs
- src/reader.rs
Results in a 5.2x speedup on a 6 CPU machine.
> Rayon usage proof of concept.

- benches/datetime.rs
- examples/add_barcode.rs
- src/object.rs
- src/parser.rs
- tests/modify.rs
Found using cargo fix this time.
> More 2018 edition lints.

- src/writer.rs
This should result in much better writing performance.
> Make write more efficient

- src/nom_parser.rs
This is many hundred times faster.
> Improve hex parsing performance.

- src/object.rs
> Handle stream filter chains

- src/creator.rs
- src/document.rs
- src/error.rs
- src/filters/png.rs
- src/lib.rs
- src/nom_parser.rs
- src/object.rs
- src/object_stream.rs
- src/parser.rs
- src/processor.rs
- src/reader.rs
- src/writer.rs
- src/xref.rs
- tests/modify.rs
This gets lopdf close to having full error signaling.
Expect more readability follow-ups.
I also removed all the unsafe code.
> Ununwrap: convert most Options to Results.

- src/document.rs
- src/processor.rs
Not much more complicated than the current get_pages. Allows some
flexibility when consuming the pages from the document.
> Page iterator

- src/document.rs
Count attributes should be reliable in the general case. This allows collecting the whole page tree with a single accurate allocation.
> Compute an accurate iterator size when the page tree is sane.

- src/datetime.rs
When chrono_time is enabled, the datetime parser is now more
permissive and will also accept a datetime format where the seconds
are missing (like in the example from the PDF spec), and also just
a date without any time information. Defaults are used for the
missing fields, as required by the PDF spec.
This change solves most of the problems pointed out in #88. The parser will still choke on some datetime strings that the spec allows. You could for example just specify a year, or only the year and month. But I assume that's rather uncommon and as far as I am concerned the issue can be closed when this change is merged.
> More permissive datetime parsing

- Cargo.toml
Those don't require any code changes.
> Update itoa and linked-hash-map

- src/error.rs
- src/filters/png.rs
- src/processor.rs
- src/reader.rs
Handle indexing errors a little friendlier than a panic.
> add indexing checks

- src/document.rs
Increase the scope of the recursion counter to the iterator instance to prevent more infinite recursion cases.
> extend recursion limit to non-local references

- src/parser.rs
- src/reader.rs
Messed up in #101, also fix now non failing test.
> Fix compilation error&test error

- src/object.rs
- src/processor.rs
I felt these convenience methods were missing.
> Add as_str, as_str_mut methods to Object

- Cargo.toml
- src/object_stream.rs
- src/reader.rs
Turn off rayon for wasm32/non-emscripten target.
> Make rayon dependency optional

- Cargo.toml
- src/content.rs
- src/creator.rs
- src/document.rs
- src/lib.rs
- src/object_stream.rs
- src/parser_aux.rs
- src/processor.rs
- src/reader.rs
- src/xobject.rs
- src/xref.rs
- tests/modify.rs
A downside is that the add_barcode example is not compiled for the nom_parser feature. I don't know how to express that, or if it is even possible. It seems like a very minor drawback though.
> Make pom dependency optional (but default)

- src/object.rs
> Added Object::as_bool

- Cargo.toml
> Update nom to 6.0

- .github/workflows/ci.yml
- pdfutil/src/main.rs
- src/creator.rs
- src/document.rs
- src/object.rs
- src/parser_aux.rs
- src/processor.rs
- src/xref.rs
- lopdf
clippy::unused_unit
clippy::iter_nth_zero
clippy::clone_on_copy
clippy::nonminimal_bool
clippy::stable_sort_primitive
clippy::or_fun_call
clippy::match_like_matches_macro
clippy::blocks_in_if_conditions
- pdfutil
clippy::len_zero
clippy::redundant_pattern
clippy::single_match
clippy::unused_must_use
> Fix clippy warnings & add clippy build job

- src/reader.rs
- src/xref.rs
> Fix `extend` definition confusion bug

- .travis.yml
- Cargo.toml
- README.md
- benches/datetime.rs
- benches/parse.rs
- examples/add_barcode.rs
- examples/create.rs
- examples/merge.rs
- src/creator.rs
- src/document.rs
- src/error.rs
- src/lib.rs
- src/nom_parser.rs
- src/object.rs
- src/parser.rs
- src/parser_aux.rs
- src/processor.rs
- src/reader.rs
- src/writer.rs
- tests/incremental_document.rs
- tests/modify.rs
- Added documentation (mainly for `Error`)
- Improved tests 
- Files are created in system's temp folder instead of CWD.
- Removed some unneeded tests (including tests if files can be deleted)
- Fixed some linting warnings.
- Added `forbid(unsafe_code)` because I don't see any reason we need unsafe code in this repo.
- Removed unused dependencies
- Added CI jobs
> Added documentation and improved tests

- README.md
- examples/create.rs
Also cleaned up a few typos in the README and added a link to the Adobe PDF reference.
Partially closes #216
> Adding Comments to examples

- Cargo.toml
- examples/rotate.rs
Closes #183
Adds a simple example of rotating pages
> Add example of page rotation

- src/document.rs
The current decryption function does not include meta info decryption.
Added logic to decrypt it.
> added meta info decryption

- src/nom_parser.rs
Hello,
In the XREF section, with generation values greater than 65535 (2¹⁶) the parsing process fails because it expects u16 but the value does not fit. This is very unlikely to happen but I found many PDF generated with this poblem (I attach one example). 
In all cases, just ignoring these entries was a valid solution and this is why I just changed the process at parsing level allowing u32 and then converting it to u16 so everything else runs as before.
With this simple change the library is a little more robust by not failing at these weird cases.
[DOC2018082312575338+18+INFORME+NECESIDAD.pdf](https://github.com/J-F-Liu/lopdf/files/13939509/DOC2018082312575338%2B18%2BINFORME%2BNECESIDAD.pdf)
> Added big generation value parsing

- src/destinations.rs
- src/document.rs
> Fix parse outline failed(#270)

- src/outlines.rs
[Uploading UNIX环境高级编程（中文第三版）.pdf…]()
In this pdf，the key 'D' in the 'Action'  dictionary is an Object Id
> Fix parse outline failed, the key ’D‘ might be an object id

- Cargo.toml
- README.md
- examples/create.rs
- src/object.rs
Resolves #281.
Reasoning on why this PR is useful can also be found in #281.
> Replace LinkedHashMap with IndexMap

- src/object_stream.rs
Fixes #287 and adds some additional error handling and logging.
> Add error handling to object stream

- src/reader.rs
> Detect reference cycles when going through trailers

- src/document.rs
- src/parser_aux.rs
> Replace unwrap with returning error

- examples/extract_text.rs
- examples/extract_toc.rs
- src/nom_cmap_parser.rs
> Fix lowercase s of Procset and no space target string(J-F-Liu#323)

- src/creator.rs
- src/parser_aux.rs
As mentioned in [issue](https://github.com/J-F-Liu/lopdf/issues/330#issuecomment-2389376658), current `extract_text` implementation leads to Err even in situations that multiple text fragments can be properly extracted.
This PR aims to improve on that by implementing a more robust `extract_text_chunks`, that will return text fragments even if some errors occurred.
Additionally some basic extract text tests have been added.
> Add function for text chunks extraction.

- Cargo.toml
- src/document.rs
- src/encryption.rs
This PR adds support for decrypting aes encrypted pdfs. Tested using a pdf with no password (empty) set.
I'm open to any suggestions or improvements
Inspired by https://github.com/Ausinero33/decrypt-pdf-stream
> Support AES encryption and revision 4

- src/xobject.rs
This PR significantly improves the efficiency of PDF processing with JPEG images, achieving 10x performance by avoiding unnecessary JPEG decode when insert JPEG into PDF.
The image buffer is now directly used as binary data when inserting JPEG images into PDF, skipping the decode step altogether. 
[image-rs](https://github.com/image-rs/image) supports retrieving the `dimensions` and `color type` without decode. This eliminates the need to decode JPEGs just to obtain these properties.
In addition, JPEG can be embedded directly into PDF as binary data. This is possible by the `DCTDecode` filter. Therefore, decoding JPEGs is redundant.
Modified the `image_from` function to accept a binary `buffer` and a file `path`. The `image_from` now checks the format of the buffer, if it is JPEG, …
> Improved JPEG Processing Efficiency by 10x

- src/destinations.rs
- src/outlines.rs
- src/toc.rs
> Fix panic in get_toc()

- src/object.rs
> remove misleading Object::as_string

- src/filters/png.rs
> Fix out of memory bug

- src/object.rs
> Replace debug assert with Result

- src/document.rs
- src/object.rs
> Also accept ASCII85 streams without EOD marker

- .vscode/settings.json
- Cargo.toml
- README.md
- examples/merge.rs
- examples/print_annotations.rs
- pdfutil/src/main.rs
- src/common_data_structures/mod.rs
- src/document.rs
- src/encodings/cmap.rs
- src/encodings/mod.rs
- src/encryption.rs
- src/error.rs
- src/lib.rs
- src/object.rs
- src/object_stream.rs
- src/outlines.rs
- src/parser/mod.rs
- src/parser_aux.rs
- src/reader.rs
- src/toc.rs
- src/writer.rs
This PR aims to rework the error in lopdf. The main goal of this rework is to make error handling more consistent in general.
I also tried to make the error messages more informative (e.g., the `ObjectType` error now tells the user which object type is expected and which type was found).
This rework was also a good opportunity to identify some code smells and fix some of them along the way.
Please let me know if you have any suggestions for improvement :)
> Rework errors

- src/parser/mod.rs
Added a trim_spaces parser that only removes spaces but not lineendings to handle startxref byte idexes with trailing spaces. This problem occured with PDFs generated by the BI software Tableau.
> Ignore space after byte index of startxref

- src/document.rs
- src/encryption.rs
This pull request fixes issue #336 (with this fix the hyperlinks in the annotations of an encrypted document are proper links instead of garbled data). In particular, not all stream and strings objects were being decrypted if they were further nested into array and/or dictionary objects.
This commit changes the `decrypt_object()` function to modify the object's content in-place replacing it with the plaintext for any encrypted stream/string object (rather than returning the plaintext). Consequently, this simplifies the `Document::decrypt()` code such that we only have to iterate over all the relevant objects and call `decrypt_object()` on each of the objects that may have to be decrypted.
In addition, this commit also extends `decrypt_object()` to recursively call `decrypt_object()` on …
> Recurse into arrays and dictionaries to fully decrypt all strings/streams

- src/encryption.rs
Ensure that the ciphertext length is a multiple of 16 bytes and avoid decryption if there is nothing to decrypt. Note that while it would be ideal to use `split_at_checked(16)` here, this would require a bump in the MSRV to 1.80. Hence, why we are currently just slicing instead. Also improve the comments a bit around the decryption code.
This partially fixes #369.
> Improve the AES decryption with some sanity checks

- src/document.rs
Upon decryption, we can finally inspect and parse the object streams that we could not handle in `Reader::read()`. This code adds the same code from `Reader::read()` to `Document::decrypt()` to add the new objects from the decrypted object stream(s), but has been simplified as we only have to deal with object streams at this point.
This partially fixes #369.
> Unpack objects after decrypting object streams

- README.md
- src/parser/mod.rs
Fix clippy warnings from newly introduced lints.
> Fix clippy

- src/encryption/algorithms.rs
While the PDF specification claims the Length field should only be present if V is 2 or 3, some newer PDF files may contain this field anyway.
* In the case V is 4, the file encryption key is 128 bits, so we simply make sure that the Length field is equal to 128 (any other option is invalid) if present. However, it should not be present for a compliant PDF file.
* In the case V is 5, the file encryption key is 256 bits, so we simply make sure that the Length field is equal to 256 (any other option is invalid) if present. However, it should not be present for a compliant PDF file.
* In the case V is 2 or 3 we simply adhere to the specification, which states the key length must be between 40 and including 128 and be divisible by 8.
* Otherwise the PDF is really not compliant to the …
> Improve Length field checks

- src/parser/mod.rs
"The colour space specified by the ColorSpace (or CS) entry shall be one of the standard device colour spaces (DeviceGray, DeviceRGB, or DeviceCMYK) and shall be present unless ImageMask (IM) is present and has the value of true."
This shows up in https://www.legislation.gov.au/C1937L00081/asmade/2025-02-21/text/original/pdf
> Inline ImageMasks don't need to have a ColorSpace so don't require one.

- src/creator.rs
PR #439 embedded fonts and attempted to inject them directly into the page’s `Resources.Font` dictionary using `get_or_create_resources`.  
However, this method creates a new resource dictionary if one doesn’t already exist, which caused incorrect references and text rendering failures.
This PR decouples font embedding from resource registration.  
Instead of modifying the page’s resource dictionary directly, `add_font` now only embeds the font and returns the corresponding `font_id`. 
It is now the caller's responsibility to register the font into the `Resources.Font` dictionary.
As a result, font references like `/F1` now work correctly without risk of corrupting or overwriting the existing resource structure.  
This also simplifies testing and improves the overall clarity of document …
> Fix font resource linkage missed in PR #439
