J-F-Liu/lopdf

src/creator.rs, src/document.rs, src/object_stream.rs, src/reader.rs, src/writer.rs, src/xref.rs, tests/modify.rs
I've refactored the API for saving and loading a bit, adding `save_to()` and `load_from()` to allow reading / writing PDF from arbitrary sources, not only files. This does not break the current API `save()` and `load()` still work.
I also added Debug for `lopdf::Document`, because the unwrap function needs this.
=> Use Read / Write for files to allow arbitrary PDF sources

src/document.rs, tests/modify.rs
I don't know why, but for some reason, the Document::get_object() was searching in the XRef table. So if I added an object, then wanted to get it again, the function couldn't find it (since it was added to the objects, not to the xref table).
For some reason it seems that `Document.streams` and `Document.reference_table` aren't used, but I'm not sure about that. If you add an object (even a stream), it gets dumped into the objects. If you want to make a function that specifically searches the XRef table, I'd rather call it `get_xref` or something like that.
An alternative way would be to add every object to the `reference_table`, but what's the point of that?
=> Changed document.get_object() to search in objects, not in XRef table

src/object.rs, src/processor.rs
For some reason, some streams in a PDF may not be compressed, while others do - such as font streams. If you compress a stream that contains an embedded font, Adobe Reader will tell you that the font is "corrupt" while other readers don't even give any error message. The text will still be selectable, but it won't show (which led me to [this](https://stackoverflow.com/questions/42754574/pdf-doesnt-show-characters-even-though-font-is-embedded-and-tounicode-is-prese)).
The problem is caused by the `Document::compress()` method ([link](https://docs.rs/lopdf/0.9.0/lopdf/struct.Document.html#method.compress)). It simply compresses every stream. Which is good for things like images, ICC profiles, etc., but embedded fonts may not be compressed (for whatever reason).
This change may break current …
=> Added optional allows_compression for Stream object

Cargo.toml, benches/datetime.rs, src/lib.rs, src/writer.rs
This commit is only performance-related.
On my flamegraph for my current application, I noticed that `lopdf::writer::write_object` uses almost 80% of it's time only formatting numbers, because of the default Rust formatter. Since I have PDFs with lots of data points (i.e. thousands of floating point numbers), this function alone used roughly 0.82% of the time on the flame graph and spends most of its time only formatting numbers:
So I asked others what an optimized way of doing this would be. The answer was to either use the `write!()` macro instead of `format!()` or to use the `itoa` and `dtoa` crates. Since the latter seem to be faster, I chose them.
Result: The CPU time is down to 0.02%. This might be due to bad measurement on my part, but I think it's logical that if you don't have to …
=> Use itoa and dtoa to improve writing performance

src/document.rs, src/xref.rs
I need this so I can clone a `printpdf::PdfDocument` when needed. This enables me to save one document to multiple files.
If you merge this, please also publish a new version on crates.io so I can let printpdf depend on that version.
=> Derive Clone for lopdf::Document

Cargo.toml, src/writer.rs
It was only used to obtain the current position, which this library can count itself. This enables saving to `&mut Vec<u8>`. This also fixed incorrect offsets if the target did not start empty.
=> Remove the Seek bound on Document::save_to

Cargo.toml, src/document.rs
Adding `get_object_mut` to `Document` so we can have the recursive dereferencing of the object which we do not have using the `objects` property directly.
I had to make a raw pointer to the `Document` so that we can have multiple mutable references in the function. It should not make any problem as we don't mutate the struct inside this function.
We could probably write it without any `unsafe` when NLL is stable.
=> add `get_object_mut`

src/datetime.rs
The +00 and -00 timezones aren't a problem because the tm_utcoff is checked for being 0 before the formatter is invoked. So on a UTC timezone, it will print the `Z`-postfixed version. Otherwise, the PR just fixes the formatting bug that I accidentally introduced in #34 and noticed here: https://github.com/J-F-Liu/lopdf/pull/34#issuecomment-423083311
=> Adress timezone formatting problem from #34

pdfutil/src/main.rs
```
= note: expected type `(u32, u16)`
found type `&(u32, {integer})`
```
=> Fix pdfutil build

src/object.rs, src/reader.rs
I noticed this while writing the nom parser.
This is to make sure this code works in reader.rs: 
```rust
if let Some(start) = stream.start_position {
let end = start + length as usize;
stream.set_content(self.buffer[start..end].to_vec());
}
```
=> Make sure Stream.start_position is relative to the whole file.

.travis.yml, Cargo.toml, benches/parse.rs, src/content.rs, src/lib.rs, src/nom_parser.rs, src/object_stream.rs, src/parser.rs, src/reader.rs
As promised, here is the nom 5 parser with the following features:
- No macros used.
- 20 to 30 times faster than the pom parser on most documents.
- Optional, enabled via the nom_parser feature.
I have also included a micro benchmark:
```
$ cargo bench --bench parse
test bench_load ... bench:     801,357 ns/iter (+/- 114,452)
```
```
$ cargo bench --bench parse --features nom_parser
test bench_load ... bench:      34,705 ns/iter (+/- 8,359)
```
Looking forward to your comments,
Jonathan
=> Nom 5 parser

Cargo.toml, src/object.rs
For implementing the functionality requested in issue #30.
The CMAP in the issue decodes to:
"/CIDInit /ProcSet findresource begin\n12 dict begin\nbegincmap\n/CMapType 2 def\n/CMapName/R99 def\n1 begincodespacerange\n<00><ff>\nendcodespacerange\n1 beginbfrange\n<20><20><0020>\nendbfrange\nendcmap\nCMapName currentdict /CMap defineresource pop\nend end\n"
As decimal bytes:
`[47, 67, 73, 68, 73, 110, 105, 116, 32, 47, 80, 114, 111, 99, 83, 101, 116, 32, 102, 105, 110, 100, 114, 101, 115, 111, 117, 114, 99, 101, 32, 98, 101, 103, 105, 110, 10, 49, 50, 32, 100, 105, 99, 116, 32, 98, 101, 103, 105, 110, 10, 98, 101, 103, 105, 110, 99, 109, 97, 112, 10, 47, 67, 77, 97, 112, 84, 121, 112, 101, 32, 50, 32, 100, 101, 102, 10, 47, 67, 77, 97, 112, 78, 97, 109, 101, 47, 82, 57, 57, 32, 100, 101, …
=> LZW decompression support

src/nom_parser.rs
Cleaner code overall and fixes the case of a backslash followed by a non-special character.
=> Escape fix

examples/add_barcode.rs, src/content.rs, src/creator.rs, src/document.rs, src/error.rs, src/lib.rs, src/nom_parser.rs, src/object.rs, src/parser.rs, src/processor.rs, src/reader.rs, src/writer.rs, src/xobject.rs, src/xref.rs, tests/modify.rs
This patch should reduce lopdf panics on practically all invalid documents.
I am not sure of the design as this is the first time I make an Error enum. Please review carefully.
I might make another patch that replaces some Options by explicit results to add precise error signaling everywhere in the future to complete this work.
=> Ununwrap: replace panics by error handling

src/parser.rs, src/processor.rs, src/reader.rs
Avoids having to go through a Readable object and a buffer copy.
=> Allow loading a document from a memory slice.

src/object_stream.rs, src/reader.rs
For now, the story for spawning threads on wasm is not entirely settled (see the conversation in rayon-rs/rayon#636), meaning that using `par_iter()` and `par_chunks()` panics in the browser.
One solution is for lopdf consumers to follow the [parallel raytracing example](https://github.com/rustwasm/wasm-bindgen/tree/master/examples/raytrace-parallel) from wasm-bindgen, but [at the time of writing](https://github.com/rustwasm/wasm-bindgen/blob/025b1d8bca8f34b056672173077578b0d4d29551/examples/raytrace-parallel/build.sh) that makes building a binary pretty non-standard.
So this PR proposes to simply disable rayon parallelisation when building for wasm, until the story for wasm threads reaches a more stable state. Let me know what you think!
=> Suggestion: don't rayon-parallelise when on wasm32

Cargo.toml, src/datetime.rs
This fixes the timezone handling issue described in #88 
Note that the other issue (handling of incomplete date strings) is not addressed by this change. I would still suggest that this is merged. Addressing the other issue will most likely be a larger effort and it would be nice to get this fixed first.
=> Fix datetime parser

src/document.rs
a self referential pdf causes infinity loop.
```pdf
%PDF-1.5
1 0 obj
<< /Type /Catalog
/Pages 2 0 R
>>
endobj
2 0 obj
<< /Type /Pages
/Kids [2 0 R]
>>
endobj
xref
1 3
0000000000 65535 f 
0000000010 00000 n 
0000000069 00000 n 
trailer
<<  /Root 1 0 R
/Size 5
>>
startxref
127
%%EOF
```
=> limit recursion to the number of objects

src/reader.rs
`%%EOF` in the content overrides the proper eof
sample:
```pdf
4 0 obj
<< /Length 55 >>
stream
BT
/F1 18 Tf
0 0 Td
(%%EOF startxref) Tj
ET
endstream
endobj
xref
0 5
0000000000 65535 f 
0000000018 00000 n 
0000000077 00000 n 
0000000178 00000 n 
0000000457 00000 n 
trailer
<<  /Root 1 0 R
/Size 5
>>
startxref
565
%%EOF
```
full pdf:
```pdf.base64
JVBERi0xLjEKJSUlJSUlJQoKMSAwIG9iagogIDw8IC9UeXBlIC9DYXRhbG9nCiAgICAgL1BhZ2Vz
IDIgMCBSCiAgPj4KZW5kb2JqCgoyIDAgb2JqCiAgPDwgL1R5cGUgL1BhZ2VzCiAgICAgL0tpZHMg
WzMgMCBSXQogICAgIC9Db3VudCAxCiAgICAgL01lZGlhQm94IFswIDAgMzAwIDE0NF0KICA+Pgpl
bmRvYmoKCjMgMCBvYmoKICA8PCAgL1R5cGUgL1BhZ2UKICAgICAgL1BhcmVudCAyIDAgUgogICAg
ICAvUmVzb3VyY2VzCiAgICAgICA8PCAvRm9udAogICAgICAgICAgIDw8IC9GMQogICAgICAgICAg
ICAgICA8PCAvVHlwZSAvRm9udAogICAgICAgICAgICAgICAgICAvU3VidHlwZSAvVHl …
```
=> keep looking for the last pattern

src/reader.rs
the pdf below triggers integer underflow
```pdf
%PDF-1.5
%%EOF
```
=> check  that the buffer is big enough for startxref

src/nom_parser.rs, src/parser.rs, src/reader.rs
Improves #97, this way the checking also applies to filtered (compressed) data.
base64 encoded sample pdf:
```
JVBERi0xLjUKMSAwIG9iajw8L1R5cGUvUGFnZXMvS2lkc1s1IDAgUl0vQ291bnQgMS9SZXNvdXJj
ZXMgMyAwIFIvTWVkaWFCb3hbMCAwIDU5NSA4NDJdPj5lbmRvYmoKMiAwIG9iajw8L1R5cGUvRm9u
dC9TdWJ0eXBlL1R5cGUxL0Jhc2VGb250L0NvdXJpZXI+PmVuZG9iagozIDAgb2JqPDwvRm9udDw8
L0YxIDIgMCBSPj4+PmVuZG9iago1IDAgb2JqPDwvVHlwZS9QYWdlL1BhcmVudCAxIDAgUi9Db250
ZW50c1s0IDAgUl0+PmVuZG9iago2IDAgb2JqPDwvVHlwZS9DYXRhbG9nL1BhZ2VzIDEgMCBSPj5l
bmRvYmoKNCAwIG9iajw8L0xlbmd0aCAgIDg0IC9GaWx0ZXIvRmxhdGVEZWNvZGU+PnN0cmVhbQp4
2u3DsQmDUBAA0P6muHRJFYUQUgcSHODABdRCPgjuX+gSdu/B+1Y8/32+PllL9F2X73NNcQcAAAAA
LjfMrW05bnubbg8AAAAA4HJZa/wqDnT6OQplbmRzdHJlYW0gZW5kb2JqCnhyZWYKMCA3CjAwMDAw
MDAwMDAgNjU1MzUgZiAKMDAwMDAwMDAwOSAwMDAwMCBuIAowMDAwMDAwMDk2IDAwMDAwIG4gC …
```
=> Move bracket depth checking into parsers.

src/parser.rs
I have some pdf files where the integer following `startxref` has trailing whitespace before the newline causing `Xref(Start)` errors. As far as I can tell, the pdf specification allows for one or more whitespace characters in many places so this seems like a bug to me.
=> Bugfix for xref_start.

src/object.rs, tests/modify.rs
This makes the function behave like the other as_xxx methods.
=> Return Result from as_array_mut()

src/content.rs, src/document.rs, src/nom_parser.rs, src/parser.rs
This was just `Vec<Operation>` before, which may be the most common use-case and is also required for parsing, since allocation is necessary.
When creating a document allocating a `Vec` per `Content` may not be necessary though, so for that use-case allowing any `AsRef<[Operation]>`, like just a slice, is convenient.
Example:
```
let content = Content {
operations: /* note the missing vec!*/[
Operation::new("BT", vec![]),
Operation::new("Tf", vec!["F1".into(), 48.into()]),
Operation::new("Td", vec![100.into(), 600.into()]),
Operation::new("Tj", vec![Object::string_literal("Hello World!")]),
Operation::new("ET", vec![]),
],
};
```
The operands for `Operation` still require `Vec`. If the `Operation` struct were to be replaced with an enum as suggested in #109 (with an additional `Custom { …
=> Genericize Content to allow AsRef<[Operation]>

README.md, examples/merge.rs, src/object.rs, src/processor.rs, src/xobject.rs
Introduction of **Dictionary** `extend()` function with a new and fixed `renumber_objects_with()` that will renumber objects ids starting from a custom ID, this is very useful in case of document merging.
I provided a working example [here](https://github.com/J-F-Liu/lopdf/pull/117/files).
=> Merge document PDF logic with some fixes

pdfutil/src/main.rs
Dearest Reviewer,
Thank you for your work on this project.  I have yet to figure out how to get it to work(`Err` value: Xref(Start)). I wanted to test my file code was correct by using this util program. Indeed my pdf is bad. The util program was broken and this helps it run.  If you do merge this it might also be nice to update the cargo program.
Dictated but not reviewed, 
Becker
```
error[E0277]: `std::result::Result<std::string::String, lopdf::Error>` doesn't implement `std::fmt::Display`
--> src/main.rs:111:19
|
111 |                         info!("{}", text);
|                                     ^^^^ `std::result::Result<std::string::String, lopdf::Error>` cannot be formatted with the default formatter
|
= help: the trait `std::fmt::Display` is not implemented for …
```
=> Unwrap the text

src/object.rs
When loading matrix (arrays) for colorspaces, sometime the 1 or 0 values are integer. Since everything can be converted to a float, I added `as_float()`.
=> Added Object::as_float() to convert numerical values to float.

src/object.rs
Use the [`Result::from_iter`] impl to collect `Result<Vec<String>>` directly.
[`Result::from_iter`]: https://doc.rust-lang.org/std/result/enum.Result.html#method.from_iter
=> Return early on error in `Stream::filters`

src/nom_parser.rs, src/parser.rs
After making the parser tests more readable I noticed that a test for the nom parser is different and was missing a `\r`.
`"(text\r\n\\\\(nested\\t\\b\\f))"`
pom: `"text\r\n\\(nested\t\x08\x0C)"`
nom: `"text\n\\(nested\t\x08\x0C)"`
This PR brings the nom parser on par with the pom parser.
=> Preserve the eol characters in literal strings

Cargo.toml, src/object.rs
Fixes: #138 
I'm unsure if this is covered by any tests. In any case, we could deactivate the `std` features if we manually do the output loop. There's not a lot to gain though. I'll also consider adding an `into_vec` adaptor to `weezl` that works with `alloc` alone and does not require the whole of `std`, let me know if this is of interest to you.
=> Replace lzw with weezl

Cargo.toml, src/creator.rs, src/parser_aux.rs
This fixes the race condition identified in issue 137:
https://github.com/J-F-Liu/lopdf/issues/137
There were several changes to fix the existing code and make adding new tests that create files more safe:
Make public helper functions to create and remove documents that can be called from other tests.
Put those helpers and the other unit tests in a tests namespace to make it clear they're for testing.
Use different filenames in different file tests (parser_aux and creator).
In creator, add a mutex around saving and reading files with the same filename.
Let me know if there are any questions or if you have any changes.
Thanks for the great work on this project.
=> Fix document save race in parser_aux::load_and_save and creator::create_document

src/writer.rs
I was trying to integrate `svg2pdf` with my crate `printpdf` in order to add the ability to convert SVG files into PDF content streams. While doing so I noticed that the resulting `FormXObject` had a wrong `/Matrix`, even though the matrix given to lopdf was correct. The `/Matrix` entry was set to `/Matrix [0.0011111111 0 0 0.0011111111 0 0]`, but when writing the file to disk, I only got `/Matrix [0.00 0.00 0.00 0.00 0.00 0.00]`, so my SVG file wasn't showing up as a result (multiplying a `cm` matrix with 0 = still 0). Also, some transformations were slightly off, and I couldn't figure out why.
This commit fixes the problem, now my SVG files show up correctly.
=> Do not limit Real precision to two digits

Cargo.toml
This is pulled in by chrono's default features.
=> Remove unneccessary time 0.1 dependency

src/parser.rs
I had to read in a PDF with a space after an `xref`, which was not accepted by `lopdf`. Since other programs can open this PDF without issue, I think `lopdf` should accept this spurious space character as well.
=> made XREF parser accept an optional space character after 'xref'

.gitignore, README.md, src/lib.rs
This patch fixes small documentation issues (like the rename of `BookMark` to `Bookmark`) and attaches README as crate level documentation using the `#[doc = include_str!]` construct. This makes the README examples run during the CI test phase.
Then the documentation is adjusted to pass tests and since now `cargo test` produces PDF files in crate level root the PDFs have been added to `.gitignore`.
By the way thanks for this great library!
=> Fix documentation issues and make README testable

README.md
Now that the examples are being run as part of the CI one of the CI tests checks if the code compiles with no default features. Since the example is dependant on one of the parsers being enabled adjust the code to check for the parser feature.
This fixes the CI build error.
=> Guard example based on if the "parser" feature is enabled

src/creator.rs, src/incremental_document.rs
The XObject resource can be a reference and needs to be properly dereferenced to be modified safely in this case.
Fix #186
=> Make add_xobject follow references

src/document.rs
Adds functions `get_dictionary_mut` and `catalog_mut` to the Document API.
=> Allow mutable access to the document catalog

src/processor.rs
Basically the issue i had is that there was a premade PDF that had pages in a certain Order. when it was loaded the first page ended up being the last page because the the ObjectID was greater than the other 3 pages.  This fixes that issue by first parsing out each page and checking and switching their ID's around. It then goes and updates the pages object Id's and swaps the old ID within any stored Objects to that of the new Page ID's. thus allowing us to reorder the pages properly and not have them swapped around. 
ATM I don't know of any better way to do this other than trans versing the objects Twice if there are pages out of order.
=> Reorder Pages before Renumbering Objects.

Cargo.toml, src/document.rs
This replaces the no longer maitained encoding crate with encoding_rs.
=> Replace unmaitained encoding crate with encoding_rs

src/parser_aux.rs
I don't think this double-pop of the graphics state stack was intentional, and it caused me difficult-to-diagnose problems a few months ago when I was trying to send something to a printing service.
=> Remove extraneous `Q` operation from `insert_image`

src/datetime.rs, src/lib.rs
Fixes #226
* Several mod/use statements in lib.rs relied on optional modules.
* `convert_utc_offset` becomes dead code if chrono is not enabled; annotated to prevent compiler warning.
=> Annotate feature usage

src/object.rs
This small PR adds two methods to `Dictionary` so that it exposes its inner hash map.
Closes #231
=> feat(lib): add `as_hashmap` and `as_hashmap_mut` to `Dictionary`

src/object.rs
To easy unit testing code to compare Object values.
And also mark StringFormat enum to be `Copy`, maybe better performance
=> Object and related types implement PartialEq

src/object.rs
`Object::String(x, StringFormat::Hexadecimal)` will now debug in accordance with PDF syntax for hexadecimal strings.
=> Add debug format for hexadecimal

src/document.rs
Some pdf using object reference instead of a dictionary
=> added object parse to get_page_fonts

src/nom_parser.rs
This fixes issue #248 where some PDFs have incorrect xrefs to objects pointing to the trailing whitespace, so the library could still handle them instead of throwing parse errors.
Specifically in this particular case the attached PDF has:
```text
xref
0 26
0000000000 65535 f
0000205013 00000 n
```
Where at offset 205013 the object begins with 0x0a:
=> Fixed parsing of the PDFs with incorrect xrefs to indirect objects

src/nom_parser.rs
Comments can be found also inside the content stream.
This is an example 
[este.pdf](https://github.com/J-F-Liu/lopdf/files/14226373/este.pdf)
Based on the metadata, it was created by Canon iR-ADV which is a photocopier that can scan documents so there should be many documents like this out there.
I tried to make the minimal changes and I also added a test
=> Accept comments in content parsing

Cargo.toml, examples/add_barcode.rs, examples/extract_text.rs, examples/extract_toc.rs, src/xobject.rs
Apologies, I needed my fork to "just work" and rushed the PR. This fixes errors found by CI which originate while running `cargo test --all-features`. All tests pass locally via single and multi-threaded.
=> Async Examples

Cargo.toml, src/destinations.rs, src/outlines.rs, src/toc.rs
Replace the use of BTreeMap with IndexMap in TOC. 
By default BTreemap is sorted ( in this case by title), so by default get_toc() returns the table of contents sorted alphabetically instead of the order they occur in the document. 
For most parsing use cases the order of TOC matters. 
Changes are minimal and just use IndexMap instead of BTreeMap.
=> Use IndexMap isntead of BTreeMap in TOC

Cargo.toml, src/encryption.rs
This replaces the `md5` crate with the more trustworthy `md-5` crate, which is maintained by the [`RustCrypto`](https://github.com/RustCrypto/.github/blob/master/profile/README.md) project.
Tests seem to pass but I haven't tested this further.
=> Replace md5 with md-5

pdfutil/README.md
Resolves #188.
Makes the README of pdfutil match the output of `pdfutil -h`.
=> Update readme of pdfutil

src/document.rs, src/error.rs
=> Detect reference cycles when collecting page resources

src/document.rs, src/error.rs, src/nom_parser.rs, src/reader.rs
Fixes #288.
Depends on #298 to be merged first.
=> Detect reference cycles when parsing streams (with nom_parser)

examples/extract_text.rs
As mentioned in #125 it looks like Unicode cmap extraction is not currently working in extract text example due to filtering of necessary keys. This PR removes the filtering of resources and fonts, thanks to which ToUnicode key from font can be properly parsed.
=> Fix Unicode fonts extraction in extract text example.

Cargo.toml
Compiling using 1.74.0 works, when using 1.73.0 the following errors are reported:
```
error[E0277]: the trait bound `Vec<u8>: From<&[u8; 9]>` is not satisfied
--> src/incremental_document.rs:82:22
|
82  |             page.set(b"Resources", Dictionary::new());
|                  --- ^^^^^^^^^^^^ the trait `From<&[u8; 9]>` is not implemented for `Vec<u8>`
|                  |
|                  required by a bound introduced by this call
|
= note: required for `&[u8; 9]` to implement `std::convert::Into<Vec<u8>>`
note: required by a bound in `Dictionary::set`
--> src/object.rs:323:12
|
321 |     pub fn set<K, V>(&mut self, key: K, value: V)
|            --- required by a bound in this associated function
322 |     where
323 |         K: Into<Vec<u8>>,
|            ^^^^^^^^^^^^^ required by …
```
=> Specify minimum Rust version in Cargo.toml

src/object.rs
Currently, calling `extend` on a `Dictionary` clears out any existing values in the dictionary. This PR reworks the method to keep existing entries, while merging in new entries from `other`.
This better matches the [semantics of the `Extend` trait](https://doc.rust-lang.org/stable/std/iter/trait.Extend.html), specifically:
> When extending a collection with an already existing key, that entry is updated or, in the case of collections that permit multiple entries with equal keys, that entry is inserted.
Fixes https://github.com/J-F-Liu/lopdf/issues/120
Fixes https://github.com/J-F-Liu/lopdf/issues/246
=> keep existing values when extending dictionary

src/reader.rs
This PR removes /Prev from the trailer when a document is loaded.
If there are incremental xref tables they will be merged into a single one, so /Prev should be discarded in all cases.
Fixes #331
=> Remove /Prev from trailer

Cargo.toml, examples/extract_text.rs, src/common_data_structures/mod.rs, src/encodings/cmap.rs, src/nom_cmap_parser.rs, src/nom_parser.rs, src/object_stream.rs, src/parser_aux.rs, src/reader.rs
* CMap parsing
* `beginbfchar` sections could have spaces separating each 2-byte character.
* In some cases, `/CIDSystemInfo` sections are encoded using a different dictionary syntax.
I also re-wired all the functions to use `LocatedSpan` from `nom_locate`. This was necessary to locate the error when debugging. I hope this is helpful, but I could also revert these changes.
A future PR could better expose this information to end users. 
Fix #334
=> Improve cmap parsing and internal error handling

src/nom_parser.rs
Some generators such as the Microsoft Reporting Services 10.0.0.0 add
an additional whitespace character after the stream keyword despite it
not being allowed in the pdf spec:
> The keyword stream that follows the stream dictionary should be
> followed by either a carriage return and a line feed or by just
> a line feed, and not by a carriage return alone.
Full credit for @IiroP for researching this. Like he mentioned in https://github.com/Tietokilta/laskugeneraattori/issues/29
[others](https://sources.debian.org/patches/pdftk/1.44-7/fix_infinite_loop_on_lf_eol/) have also had issues with this.
I think it is better to support this than to just refuse to parse the pdf-files. 
Let me know if you want me to include a warning for not following the spec or something.
=> fix(parser): allow whitespace after stream keyword

pdfutil/src/main.rs
The --merge flag takes an arbritary list of pdfs and merges them into one.
Example:
pdfutil --merge A.pdf B.pdf --output C.pdf
Optionally it can be run without the --output flag, then it will save to merged.pdf.
If only 1 is given it will just create a copy of the original pdf.
The merge code is taken from examples/merge.rs. I use the layer variable to avoid the borrow checker from complaining when using .iter().enumerate().
=> pdfutil: Add ability to merge pdfs

src/object.rs, src/object_stream.rs, src/parser_aux.rs, src/processor.rs
When loading documents, return an error if an xref stream cannot be uncompressed due to an unsupported filter or any other problem.
Fixes #338
=> Throw error if xref stream cannot be uncompressed

src/reader.rs
Fixes #311.
The error occurred when the xref table/stream contained a too big object ID.
=> Fix addition overflow

src/encryption.rs, src/object.rs
Fixes #321.
Formatting in `encryption.rs`
=> Fix mulitplication overflow in ascii85 decode

src/nom_parser.rs, src/parser/mod.rs
This pull request lays the groundwork to properly support inline images.
What makes inline images hard to support, is that they include a data stream of arbitrary bytes and unknown length. If the (final) filter on the stream has an EOD marker, finding the end isn't that hard (although it isn't hard, this PR doesn't implement it).
If the (final) filter doesn't have an EOD marker, it's much harder to find the end, as it effectively forces the us to decompress the stream.
This PR addresses #78 and #221, but I wouldn't say that the issue is resolved. In practice, the images are compressed in some way, and this PR doesn't implement that.
=> Inline images

src/parser/mod.rs
Whether this should be supported is a philosophical question, but the fact is that some PDF files have prefixes before the header. 
As I understand it, this is contrary to the spec, but dates to the origins of Acrobat, which supported up to 1024 bytes of garbage before the actual header.
Implementations now either rely on it or generate it accidentally, but such files are still generated.
I think lopdf should support this bug, and allow reading more PDFs even if they're not to-spec.
=> Allow parsing off-spec PDF files with prefixes before the header

src/bookmarks.rs
Currently, `lopdf` generates garbled text when handling bookmark titles containing non-ASCII characters. This issue arises because the PDF specification requires bookmark titles to be encoded in `UTF-16BE`, with a Byte Order Mark (BOM) to correctly parse non-ASCII characters. However, the existing implementation directly uses the value of bookmark.title without properly encoding non-ASCII characters.
This PR determine if the bookmark title is ASCII:
- If it is ASCII, use the original bytes directly.
- If it is not ASCII, convert the title to UTF-16BE encoding.
Tested with Chinese ("例子"), Russian ("Пример"), and Arabic ("أمثلة") in bookmark titles, all of which displayed correctly in Edge's PDF viewer.
No significant impact on performance for ASCII titles.
For non-ASCII titles, there is an …
=> Support Non-ASCII Bookmark Title

src/document.rs
Commit 9f22915 introduces a regression in 0.35 compared to 0.34 when decrypting a PDF document that does not use AES. Instead of decrypting the document, it throws an error that the CF dictionary is missing. Consequently, this prevents the document from being decrypted.
To remedy this, this pull request eliminates all uses of `?` in the `is_aes` check to gracefully determine if the PDF document uses AES or not. It then proceeds to decrypt it accordingly.
Instead of using `?`, we carefully convert all `Result<T, E>` types into `Option<T>` using `.ok()` in combination with `.map()` and `.flatten()` to walk through the series of dictionaries. Then at the final step we simply compare if the `cfm` is equal to `b"AESV2"`. If any of the steps fails, we would get `None`, in which case we default …
=> Gracefully handle the is_aes check without throwing errors

src/document.rs
Fix issue #373 replacing `page_tree.get(b"Kids")` with the proposed `page_tree.get_deref(b"Kids", doc)` to handle the possibility of indirect references for the `Kids` array.
=> Use get_deref for the Kids array to handle indirect references

src/encryption.rs
According to the PDF 1.7 specification cross-reference streams shouldn't be encrypted. Add a check if the stream is a cross-reference stream and do nothing if it is.
This partially fixes #369.
=> Avoid decrypting cross-reference streams

src/document.rs, src/reader.rs
OK, after testing upstream to make sure lopdf works for issue #369, I realized some things were still missing.
The first commit makes sure that `Reader::read()` does not try to parse object streams when the document is encrypted, thus leaving them intact for `Document::decrypt()` such that it can parse the object streams after decrypting the streams.
The second commit fixes #382. I was somehow missing a `continue` after checking that the stream is **not** an object stream as well as the part to actually add the newly parsed objects.
I tested this branch to make sure this all works for the document provided in issue #369 and everything looks good now.
=> Avoid parsing encrypted object streams early and correctly parse object streams upon decryption

Cargo.toml, src/creator.rs, src/datetime.rs
Rather than having a `chrono_time` toggle, this pull request introduces separate feature flags for the [chrono](https://docs.rs/chrono/latest/chrono/) and [time](https://docs.rs/chrono/latest/time/) crates. In addition, this pull request adds support for the new [jiff](https://docs.rs/chrono/latest/jiff/) crate. While all dependencies are enabled by default, this ultimately gives users more control over which dependencies they want to use to handle dates and times.
Unfortunately, this pull request introduces a **breaking API change (!)** to provide this level of compatibility as `Object::as_datetime()` had varying implementations depending on whether the original `chrono_time` feature was enabled or disabled. Instead, this pull request introduces a `DateTime` struct to hold the `String` …
=> Add support for jiff and make both chrono and time optional features

src/document.rs, src/encryption.rs, src/error.rs
This pull request adds support for PDF documents encrypted with 256-bit AES-CBC and PDF documents that make use of crypt filters.
Since this is a rather large pull request, let me summarize each of the commits:
The first commit introduces a `CryptFilter` trait responsible for computing the key to be used to decrypt the ciphertext of a given string or stream object as well as decrypting said ciphertext. In addition, it implements a `Rc4CryptFilter`, an `Aes128CryptFilter` and an `IdentityCryptFilter` to handle the existing key computation and decryption. The `IdentityFilter` is essentially a no-op and is required by the specification where the `Identity` crypt filter is used to passthrough the ciphertext unaltered as plaintext. In addition, this commits adds some comments around the key …
=> Crypt filters

Cargo.toml, src/encryption.rs, src/toc.rs
This pull request implements PKCS#5 padding rather than using PKCS#7 padding to better adhere to the PDF specification which states that AES encryption should use PKCS#5 padding.
In addition, this pull request starts initial work on being able to encrypt documents by adding `encrypt()` to the `CryptFilter` trait, implementing the `encrypt()` function for the various existing crypt filters and implementing `encrypt_object()` (which can later be used by `Document::encrypt()` once the remaining password algorithms are in place).
=> Use PKCS#5 and implement encryption logic

.github/workflows/ci.yml, Cargo.toml, src/lib.rs, src/object_stream.rs, src/parser/mod.rs, src/parser_aux.rs, src/reader.rs, src/xref.rs
This will produce a clippy warning until commit 72be7e7 gets merged (currently part of PR #388, but let me know if you want me to open a separate pull request to fix the clippy warning. I think it is the result of a new clippy version).
This pull request attempts to fix #374 by removing the `nom_parser` feature flag entirely, which enables nom by default regardless of what feature flags are set. Since the removal of pom in #355, I don't think there is anything but nom left, so it makes sense to just remove the `nom_parser` feature flag to have this work properly. However, reviews are welcome to make sure I am not missing anything here.
Closes #374.
=> Remove nom_parser feature flag

Cargo.toml, src/parser_aux.rs, tests/annotation.rs, tests/incremental_document.rs, tests/modify.rs, tests/unicode.rs
This pull request fixes some warnings about some remnant nom_parser feature flag checks, unused imports and nom_parser is no longer a required feature for the rotate example.
=> Fix a number of warnings

src/reader.rs
I would like to hear some opinions on this.
What I propose is, when reading a document that has a binary comment, discard it as we do with any other comments and always write our own binary comment.
Fixes #391
=> Replace binary comment with the default one

Cargo.toml, src/document.rs, src/encryption.rs, src/encryption/algorithms.rs, src/encryption/crypt_filters.rs, src/error.rs
Since this pull request is getting quite large already, I am leaving the work of implementing more sanity checks in terms of what is possible depending on the version/revision, actual test cases and an `EncryptionStateBuilder` when creating new PDF documents for the next pull request, but I think those are the tasks that are currently left to do.
This pull request implements `Document::encrypt()`. 
The `EncryptionState` has been reworked to store all the relevant pieces of information from the encrypted dictionary, that way we can encode it back to an encrypted dictionary when encrypting it. The decoding logic has also been moved into `EncryptionState::decode()`. In addition, some fixes were required to make this work such as storing the default stream/string crypt filters by name and …
=> Implement Document::encrypt()

examples/decrypt.rs, examples/encrypt.rs, src/document.rs, src/encryption.rs, src/encryption/algorithms.rs, src/encryption/crypt_filters.rs, src/lib.rs
This pull request adds a number of sanity checks to the PDF decryption/encryption logic following the PDF specification closely, but not too closely to avoid real-world documents from breaking (the specification has some conflicting statements and can be a bit ambiguous here and there).
In addition, this pull request implements `EncryptionVersion` which can be used to construct an `EncryptionState` to pas to `Document::encrypt()`. This is basically an enum for different encryption versions. Depending on the version, the user needs to pass different bits of information.
This pull request also adds two examples. `example/decrypt.rs` is essentially a tool that can decrypt a PDF and save the resulting PDF without any encryption, whereas `example/encrypt.rs` can be used to encrypt a given …
=> Add sanity checks for PDF encryption, add examples for decrypting/encrypting PDF files and various bug fixes

examples/encrypt.rs, src/encryption.rs, src/encryption/crypt_filters.rs
This PR adds a few more commits to harden the encryption/decryption logic in lopdf a bit more against invalid inputs.
The first commit ensures that the file encryption length is always 128 bits. It basically sets the Length file to 128 bits and removes the explicit length field in `EncryptionVersion::V4`.
The second commit adds checks to the AES crypt filters to ensure that the key length is 16 bytes for 128-bit AES and 32 bytes for 256-bit AES and returns errors (instead of potentially causing a panic).
The third commit removes `.unwrap()` in the AES crypt filters when invalid padding is encountered. This can happen during decryption when the file encryption key is simply not the actual file encryption key that was used to encrypt the streams (e.g., in PDF 2.0 it is possible to store a …
=> Add more checks to the encryption/decryption logic

src/encryption.rs
Only encode the `EncryptMetadata` field for V >= 4. It's fine if it is present for lower values of V as PDF readers should ignore it, but ideally it shouldn't be encoded in those cases.
=> Only encode EncryptMetadata for V >= 4

src/encryption.rs, src/encryption/algorithms.rs
Revision 5 was once used by a proprietary Adobe extension, but should not be used to produce new documents. It is almost identical to revision 6, but short-circuits the hash algorithm by simply returning the initial SHA-256 hash. We want to support this on the decryption side to make it possible to read such documents, and on the encryption side to test that this works correctly.
The first commit adds an early return of the SHA-256 hash in the hash algorithm when the revision is 5.
The second commit re-uses the R6 algorithms for R5 as these are identical.
The third commit adds the `R5` variant to `EncryptionVersion` allowing us to implement tests to ensure that the decryption works correctly.
The fourth commit adds a deprecation warning which should warn users if they try to use …
=> Add support for Revision 5

Cargo.toml, src/parser/cmap_parser.rs, src/parser/mod.rs
Update nom to version 8.0 and nom_locate to version 5.0.
Most notably, nom merged the various traits into a single `Input` trait, which means that the `Slice` trait no longer exists. So we have to replace every `tag(b"xyz")` with `tag(&b"xyz"[..])`. Furthermore, nom 8.0 returns a `Parser` trait instead of closures, which means that we have to call `parser.parse(input)` rather than `parser(input)`. Other than that, some minimal changes are required such as fixing the function signature of `trim_spaces()`  and replacing the discard functions in `parser_aux.rs` with `.map(|(i, _)| (i, ()))` or `.map(|_| ())` to discard the result.
=> Update to nom 8.0 and nom_locate 5.0

examples/encrypt.rs
Randomly generate the file encryption key for V5 in the encrypt example rather than use a zero key.
=> Randomly generate file encryption key for V5 in encrypt example

src/encryption/algorithms.rs
Update the validation logic in `TryFrom<&Document> for PasswordAlgorithm` to also check the presence and the length of fields in revision 5 documents.
Fixes issue #404.
=> Validate encryption dictionary for revision 5

src/creator.rs, src/encryption.rs, src/encryption/algorithms.rs
This PR implements test cases for the password algorithms and document encryption/decryption. It also fixes a bug where the OE, UE and Perms field didn't get encoded for R5 (spotted this issue thanks to the tests).
=> Implement test cases for encryption

src/document.rs
=> Avoid unwrapping object streams when decrypting documents

.github/workflows/ci.yml, Cargo.toml
Set up a workflow for `wasm32-unknown-unknown` using wasm-pack to ensure that lopdf builds for WebAssembly targets.
See also #408.
=> Set up WASM CI workflow

.github/workflows/ci.yml
Set up CI workflows to build lopdf for wasm32-wasip1 and wasm32-wasip2, but avoid running `cargo test` for now. `cargo test` seems to require Rust nightly and `#![feature(wasip2)]` somewhere due to the tempfile dependency.
See also issue #408.
=> Set up WASI CI

src/encryption.rs, src/encryption/algorithms.rs
Correctly fix the issue presented in #413 in which non-compliant PDF files may have a P-value that does not have the reserved bits set correctly:
* Remove the `p_value()` method from `Permissions` entirely.
* Replace all instances of `Permissions::p_value()` with `Permissions::bits()`.
* Use `from_bits_retain()` rather than `from_bits_truncate()` to preserve the state of the reserved bits from the PDF. This is necessary to derive the correct file encryption key.
* Move the logic from `Permissions::p_value()` to `Permissions::correct_bits()`, which we call when encrypting documents, such that when encrypting new/existing documents with lopdf, we always produce compliant PDF files where the reserved bits in the P-value contain the correct state.
The clippy test is expected to fail until …
=> Retain permission bits

src/encryption/algorithms.rs
Rather than decrypting/encrypting a single block of 16 bytes, change the code to iterate over blocks (like we do everywhere else). Since the plaintext/ciphertext is only 16 bytes, it doesn't change anything, but the consistency should improve the readability of the code.
=> Improve readability by consistently iterating over blocks

src/creator.rs
The `add_object()` method adds an object into the object list.
Now, I would assume that `remove_object()` would do the opposite. However, looking at [the source](https://github.com/J-F-Liu/lopdf/blob/4003a9e4a6feb1ae2c2b961455f71981a5f6de70/src/creator.rs#L31), the method instead goes through all the pages and tries to remove the object from the page's annotations (failing if there's no `Annots` entry).
I think that should be changed. Or is there any other way to just delete the object in question?
=> Change remove_object() to only remove the object
